name: CICD

on:
  push:
    branches: ["**"]

jobs:
  java-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven build
        run: |
          ./mvnw --batch-mode verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar
          retention-days: 2
  docker-build:
    runs-on: ubuntu-latest
    needs: java-build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: target
      - name: Docker build
        run: docker build -t loan-app .