name: CICD

on:
  push:
    branches: ["**"]

jobs:
  java-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven build
        run: |
          ./mvnw --batch-mode verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar
          retention-days: 2
  docker-build:
    runs-on: ubuntu-latest
    needs: java-build-test
    env:
      IMAGE_TAG: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPOSITORY }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: target
      - name: Docker build
        run: docker build -t ${{ env.IMAGE_TAG }} .
      - name: Docker push
        run: docker push ${{ env.IMAGE_TAG }}
